In [3]:

import pandas as pd

df_csv = pd.read_csv("/content/exp2_import_export_120.csv")
print("CSV Data:")
display(df_csv.head())

df_csv.to_excel("/content/exp2_import_export_120.xlsx", index=False)

df_excel = pd.read_excel("/content/exp2_import_export_120.xlsx")
print("Excel Data:")
display(df_excel.head())

url = "https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)"

try:
    tables = pd.read_html(url)
    df_web = tables[0]
    print("Web Data:")
    display(df_web.head())
except Exception as e:
    print("Web import unavailable:", e)

df_csv.to_excel("/content/exp2_exported_data.xlsx", index=False)
print("Data exported successfully.")

CSV Data:

  Order_ID        Date Region     Category  Quantity  UnitPrice CustomerType
0    O0001  2025-01-01  South      Grocery        14       2818          New
1    O0002  2025-01-04   East        Books        11       3323          New
2    O0003  2025-01-07  North  Electronics         7       1320          New
3    O0004  2025-01-10   East        Books         5        918          New
4    O0005  2025-01-13  North        Books        13       1636    Returning

Excel Data:

  Order_ID        Date Region     Category  Quantity  UnitPrice CustomerType
0    O0001  2025-01-01  South      Grocery        14       2818          New
1    O0002  2025-01-04   East        Books        11       3323          New
2    O0003  2025-01-07  North  Electronics         7       1320          New
3    O0004  2025-01-10   East        Books         5        918          New
4    O0005  2025-01-13  North        Books        13       1636    Returning

Web import unavailable: HTTP Error 403: Forbidden
Data exported successfully.